### ISSUE TITLE
Enable/Disable functionality broken for all streams

### ISSUE THREAD

**Issue by ravazquez** [vvvv/VL.Devices.Kinect2#1]
After introducing the new infrastructure to handle Image memcopy properly using Subjects, previousy working Enable/Disable input pins in Kinect2 node stopped working. The Kinect sensor remains active even after deleting the nodes altogether. Only closing gamma seems to release the sensor.

**Comment by azeno** [comment]
Hm had a look at the patches for 10 min but can't really see anything obvious. You say it worked before? What was the essential difference again? You copied all the time?

**Comment by ravazquez** [comment]
Fixed in https://github.com/vvvv/VL.Devices.Kinect2/tree/observable-based branch and merged to master on 74e71b8eddf69a75ba4cbcc465c45414541ecf00
