### ISSUE TITLE
Support for pixel format R32G32_Float is needed in VL.Lib.Basics.Imaging

### ISSUE THREAD

**Issue by ravazquez** [vvvv/VL.Devices.Kinect2#2]
Output of RGBDepth and DepthRGB nodes is in R32G32_Float format, VL.Lib.Basics.Imaging does not support such fromat.

**Comment by azeno** [comment]
Just added it to VL.Core as well as IImage to vvvv beta texture converters. You'll have to wait on a build including the change though.
